[project]
name = "standardebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "lxml",
    "pyarrow",
    "tqdm",
    "beautifulsoup4",
    "pyyaml",
    "gitpython",
    "markdownify",
]
